[package]
name = "mokRadio"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
mp3-duration = "0.1.10"
rand = "0.9.2"
rodio = "0.21.1"
serde = { version = "1.0.226", features = ["derive"] }
serde_json = "1.0.145"
